// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agent/v1/summary/summary.proto

package summary

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_agent_v1_summary_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_summary_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_summary_summary_proto_rawDescGZIP(), []int{0}
}

func (x *GetSummaryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSummaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Resp          string                 `protobuf:"bytes,3,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryReply) Reset() {
	*x = GetSummaryReply{}
	mi := &file_agent_v1_summary_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryReply) ProtoMessage() {}

func (x *GetSummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_summary_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryReply.ProtoReflect.Descriptor instead.
func (*GetSummaryReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_summary_summary_proto_rawDescGZIP(), []int{1}
}

func (x *GetSummaryReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSummaryReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSummaryReply) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_agent_v1_summary_summary_proto protoreflect.FileDescriptor

const file_agent_v1_summary_summary_proto_rawDesc = "" +
	"\n" +
	"\x1eagent/v1/summary/summary.proto\x12\x14api.agent.v1.summary\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\x11GetSummaryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x0fGetSummaryReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04resp\x18\x03 \x01(\tR\x04resp2\x90\x01\n" +
	"\aSummary\x12\x84\x01\n" +
	"\x10GetRecentSummary\x12'.api.agent.v1.summary.GetSummaryRequest\x1a%.api.agent.v1.summary.GetSummaryReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/agent/summary/recentB@\n" +
	"\x14api.agent.v1.summaryP\x01Z&cwxu-algo/api/agent/v1/summary;summaryb\x06proto3"

var (
	file_agent_v1_summary_summary_proto_rawDescOnce sync.Once
	file_agent_v1_summary_summary_proto_rawDescData []byte
)

func file_agent_v1_summary_summary_proto_rawDescGZIP() []byte {
	file_agent_v1_summary_summary_proto_rawDescOnce.Do(func() {
		file_agent_v1_summary_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_summary_summary_proto_rawDesc), len(file_agent_v1_summary_summary_proto_rawDesc)))
	})
	return file_agent_v1_summary_summary_proto_rawDescData
}

var file_agent_v1_summary_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_v1_summary_summary_proto_goTypes = []any{
	(*GetSummaryRequest)(nil), // 0: api.agent.v1.summary.GetSummaryRequest
	(*GetSummaryReply)(nil),   // 1: api.agent.v1.summary.GetSummaryReply
}
var file_agent_v1_summary_summary_proto_depIdxs = []int32{
	0, // 0: api.agent.v1.summary.Summary.GetRecentSummary:input_type -> api.agent.v1.summary.GetSummaryRequest
	1, // 1: api.agent.v1.summary.Summary.GetRecentSummary:output_type -> api.agent.v1.summary.GetSummaryReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_v1_summary_summary_proto_init() }
func file_agent_v1_summary_summary_proto_init() {
	if File_agent_v1_summary_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_summary_summary_proto_rawDesc), len(file_agent_v1_summary_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_summary_summary_proto_goTypes,
		DependencyIndexes: file_agent_v1_summary_summary_proto_depIdxs,
		MessageInfos:      file_agent_v1_summary_summary_proto_msgTypes,
	}.Build()
	File_agent_v1_summary_summary_proto = out.File
	file_agent_v1_summary_summary_proto_goTypes = nil
	file_agent_v1_summary_summary_proto_depIdxs = nil
}
