// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: agent/v1/summary/summary.proto

package summary

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSummaryGetRecentSummary = "/api.agent.v1.summary.Summary/GetRecentSummary"

type SummaryHTTPServer interface {
	GetRecentSummary(context.Context, *GetSummaryRequest) (*GetSummaryReply, error)
}

func RegisterSummaryHTTPServer(s *http.Server, srv SummaryHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/agent/summary/recent", _Summary_GetRecentSummary0_HTTP_Handler(srv))
}

func _Summary_GetRecentSummary0_HTTP_Handler(srv SummaryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSummaryGetRecentSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRecentSummary(ctx, req.(*GetSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSummaryReply)
		return ctx.Result(200, reply)
	}
}

type SummaryHTTPClient interface {
	GetRecentSummary(ctx context.Context, req *GetSummaryRequest, opts ...http.CallOption) (rsp *GetSummaryReply, err error)
}

type SummaryHTTPClientImpl struct {
	cc *http.Client
}

func NewSummaryHTTPClient(client *http.Client) SummaryHTTPClient {
	return &SummaryHTTPClientImpl{client}
}

func (c *SummaryHTTPClientImpl) GetRecentSummary(ctx context.Context, in *GetSummaryRequest, opts ...http.CallOption) (*GetSummaryReply, error) {
	var out GetSummaryReply
	pattern := "/v1/agent/summary/recent"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSummaryGetRecentSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
