// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: user/v1/profile/profile.proto

package profile

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	EmailEnabled  bool                   `protobuf:"varint,8,opt,name=emailEnabled,proto3" json:"emailEnabled,omitempty"`
	RoleId        int32                  `protobuf:"varint,9,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Spiders       []*GetByIdRes_Spiders  `protobuf:"bytes,7,rep,name=spiders,proto3" json:"spiders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRes) Reset() {
	*x = GetByIdRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRes) ProtoMessage() {}

func (x *GetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRes.ProtoReflect.Descriptor instead.
func (*GetByIdRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRes) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetByIdRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetByIdRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetByIdRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetByIdRes) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetByIdRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetByIdRes) GetEmailEnabled() bool {
	if x != nil {
		return x.EmailEnabled
	}
	return false
}

func (x *GetByIdRes) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *GetByIdRes) GetSpiders() []*GetByIdRes_Spiders {
	if x != nil {
		return x.Spiders
	}
	return nil
}

type GetByNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByNameReq) Reset() {
	*x = GetByNameReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByNameReq) ProtoMessage() {}

func (x *GetByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByNameReq.ProtoReflect.Descriptor instead.
func (*GetByNameReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetByNameRes struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	List          []*GetByNameRes_UserList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByNameRes) Reset() {
	*x = GetByNameRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByNameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByNameRes) ProtoMessage() {}

func (x *GetByNameRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByNameRes.ProtoReflect.Descriptor instead.
func (*GetByNameRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetByNameRes) GetList() []*GetByNameRes_UserList {
	if x != nil {
		return x.List
	}
	return nil
}

type GetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int64                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNum       int64                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type GetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GetListRes_List     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes) Reset() {
	*x = GetListRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes) ProtoMessage() {}

func (x *GetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes.ProtoReflect.Descriptor instead.
func (*GetListRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *GetListRes) GetList() []*GetListRes_List {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MoveGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveGroupReq) Reset() {
	*x = MoveGroupReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveGroupReq) ProtoMessage() {}

func (x *MoveGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveGroupReq.ProtoReflect.Descriptor instead.
func (*MoveGroupReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{8}
}

func (x *MoveGroupReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MoveGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MoveGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveGroupRes) Reset() {
	*x = MoveGroupRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveGroupRes) ProtoMessage() {}

func (x *MoveGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveGroupRes.ProtoReflect.Descriptor instead.
func (*MoveGroupRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{9}
}

func (x *MoveGroupRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MoveGroupRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetEmailEnabledReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmailEnabledReq) Reset() {
	*x = SetEmailEnabledReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmailEnabledReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmailEnabledReq) ProtoMessage() {}

func (x *SetEmailEnabledReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmailEnabledReq.ProtoReflect.Descriptor instead.
func (*SetEmailEnabledReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{10}
}

func (x *SetEmailEnabledReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetEmailEnabledReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetEmailEnabledRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEmailEnabledRes) Reset() {
	*x = SetEmailEnabledRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEmailEnabledRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEmailEnabledRes) ProtoMessage() {}

func (x *SetEmailEnabledRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEmailEnabledRes.ProtoReflect.Descriptor instead.
func (*SetEmailEnabledRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{11}
}

func (x *SetEmailEnabledRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetEmailEnabledRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserIdsByGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdsByGroupReq) Reset() {
	*x = GetUserIdsByGroupReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdsByGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdsByGroupReq) ProtoMessage() {}

func (x *GetUserIdsByGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdsByGroupReq.ProtoReflect.Descriptor instead.
func (*GetUserIdsByGroupReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserIdsByGroupReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetUserIdsByGroupRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdsByGroupRes) Reset() {
	*x = GetUserIdsByGroupRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdsByGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdsByGroupRes) ProtoMessage() {}

func (x *GetUserIdsByGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdsByGroupRes.ProtoReflect.Descriptor instead.
func (*GetUserIdsByGroupRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserIdsByGroupRes) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdsReq) Reset() {
	*x = GetByIdsReq{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdsReq) ProtoMessage() {}

func (x *GetByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdsReq.ProtoReflect.Descriptor instead.
func (*GetByIdsReq) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{14}
}

func (x *GetByIdsReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetByIdsRes struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Profiles      []*GetByIdsRes_UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdsRes) Reset() {
	*x = GetByIdsRes{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdsRes) ProtoMessage() {}

func (x *GetByIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdsRes.ProtoReflect.Descriptor instead.
func (*GetByIdsRes) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{15}
}

func (x *GetByIdsRes) GetProfiles() []*GetByIdsRes_UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type GetByIdRes_Spiders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRes_Spiders) Reset() {
	*x = GetByIdRes_Spiders{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRes_Spiders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRes_Spiders) ProtoMessage() {}

func (x *GetByIdRes_Spiders) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRes_Spiders.ProtoReflect.Descriptor instead.
func (*GetByIdRes_Spiders) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetByIdRes_Spiders) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetByIdRes_Spiders) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetByNameRes_UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByNameRes_UserList) Reset() {
	*x = GetByNameRes_UserList{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByNameRes_UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByNameRes_UserList) ProtoMessage() {}

func (x *GetByNameRes_UserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByNameRes_UserList.ProtoReflect.Descriptor instead.
func (*GetByNameRes_UserList) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetByNameRes_UserList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetByNameRes_UserList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListRes_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LastSubmit    string                 `protobuf:"bytes,7,opt,name=lastSubmit,proto3" json:"lastSubmit,omitempty"`
	RoleId        int32                  `protobuf:"varint,8,opt,name=roleId,proto3" json:"roleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes_List) Reset() {
	*x = GetListRes_List{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes_List) ProtoMessage() {}

func (x *GetListRes_List) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes_List.ProtoReflect.Descriptor instead.
func (*GetListRes_List) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetListRes_List) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetListRes_List) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetListRes_List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListRes_List) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetListRes_List) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetListRes_List) GetLastSubmit() string {
	if x != nil {
		return x.LastSubmit
	}
	return ""
}

func (x *GetListRes_List) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetByIdsRes_UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdsRes_UserProfile) Reset() {
	*x = GetByIdsRes_UserProfile{}
	mi := &file_user_v1_profile_profile_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdsRes_UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdsRes_UserProfile) ProtoMessage() {}

func (x *GetByIdsRes_UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_profile_profile_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdsRes_UserProfile.ProtoReflect.Descriptor instead.
func (*GetByIdsRes_UserProfile) Descriptor() ([]byte, []int) {
	return file_user_v1_profile_profile_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GetByIdsRes_UserProfile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetByIdsRes_UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetByIdsRes_UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_user_v1_profile_profile_proto protoreflect.FileDescriptor

const file_user_v1_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1duser/v1/profile/profile.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"GetByIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xd6\x02\n" +
	"\n" +
	"GetByIdRes\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\"\n" +
	"\femailEnabled\x18\b \x01(\bR\femailEnabled\x12\x16\n" +
	"\x06roleId\x18\t \x01(\x05R\x06roleId\x129\n" +
	"\aspiders\x18\a \x03(\v2\x1f.api.user.v1.GetByIdRes.SpidersR\aspiders\x1aA\n" +
	"\aSpiders\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\"\n" +
	"\fGetByNameReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\fGetByNameRes\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".api.user.v1.GetByNameRes.UserListR\x04list\x1a6\n" +
	"\bUserList\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\n" +
	"GetListReq\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x03R\bpageSize\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x03R\apageNum\"\x8f\x02\n" +
	"\n" +
	"GetListRes\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.api.user.v1.GetListRes.ListR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x1a\xb8\x01\n" +
	"\x04List\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x1e\n" +
	"\n" +
	"lastSubmit\x18\a \x01(\tR\n" +
	"lastSubmit\x12\x16\n" +
	"\x06roleId\x18\b \x01(\x05R\x06roleId\"e\n" +
	"\tUpdateReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"9\n" +
	"\tUpdateRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\fMoveGroupReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\agroupId\x18\x02 \x01(\x03R\agroupId\"<\n" +
	"\fMoveGroupRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12SetEmailEnabledReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"B\n" +
	"\x12SetEmailEnabledRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x14GetUserIdsByGroupReq\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\"0\n" +
	"\x14GetUserIdsByGroupRes\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\x03R\auserIds\"'\n" +
	"\vGetByIdsReq\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\x03R\auserIds\"\xa2\x01\n" +
	"\vGetByIdsRes\x12@\n" +
	"\bprofiles\x18\x01 \x03(\v2$.api.user.v1.GetByIdsRes.UserProfileR\bprofiles\x1aQ\n" +
	"\vUserProfile\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar2\xe8\x06\n" +
	"\aProfile\x12_\n" +
	"\aGetById\x12\x17.api.user.v1.GetByIdReq\x1a\x17.api.user.v1.GetByIdRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/profile/get-by-id\x12g\n" +
	"\tGetByName\x12\x19.api.user.v1.GetByNameReq\x1a\x19.api.user.v1.GetByNameRes\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/user/profile/get-by-name\x12Z\n" +
	"\aGetList\x12\x17.api.user.v1.GetListReq\x1a\x17.api.user.v1.GetListRes\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/user/profile/list\x12\\\n" +
	"\x06Update\x12\x16.api.user.v1.UpdateReq\x1a\x16.api.user.v1.UpdateRes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/user/profile/update\x12i\n" +
	"\tMoveGroup\x12\x19.api.user.v1.MoveGroupReq\x1a\x19.api.user.v1.MoveGroupRes\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/user/profile/move-group\x12\x82\x01\n" +
	"\x0fSetEmailEnabled\x12\x1f.api.user.v1.SetEmailEnabledReq\x1a\x1f.api.user.v1.SetEmailEnabledRes\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/user/profile/set-email-enabled\x12\x80\x01\n" +
	"\x11GetUserIdsByGroup\x12!.api.user.v1.GetUserIdsByGroupReq\x1a!.api.user.v1.GetUserIdsByGroupRes\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/user/profile/ids-by-group\x12f\n" +
	"\bGetByIds\x12\x18.api.user.v1.GetByIdsReq\x1a\x18.api.user.v1.GetByIdsRes\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/user/profile/get-by-idsB6\n" +
	"\vapi.user.v1P\x01Z%cwxu-algo/api/user/v1/profile;profileb\x06proto3"

var (
	file_user_v1_profile_profile_proto_rawDescOnce sync.Once
	file_user_v1_profile_profile_proto_rawDescData []byte
)

func file_user_v1_profile_profile_proto_rawDescGZIP() []byte {
	file_user_v1_profile_profile_proto_rawDescOnce.Do(func() {
		file_user_v1_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_profile_profile_proto_rawDesc), len(file_user_v1_profile_profile_proto_rawDesc)))
	})
	return file_user_v1_profile_profile_proto_rawDescData
}

var file_user_v1_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_v1_profile_profile_proto_goTypes = []any{
	(*GetByIdReq)(nil),              // 0: api.user.v1.GetByIdReq
	(*GetByIdRes)(nil),              // 1: api.user.v1.GetByIdRes
	(*GetByNameReq)(nil),            // 2: api.user.v1.GetByNameReq
	(*GetByNameRes)(nil),            // 3: api.user.v1.GetByNameRes
	(*GetListReq)(nil),              // 4: api.user.v1.GetListReq
	(*GetListRes)(nil),              // 5: api.user.v1.GetListRes
	(*UpdateReq)(nil),               // 6: api.user.v1.UpdateReq
	(*UpdateRes)(nil),               // 7: api.user.v1.UpdateRes
	(*MoveGroupReq)(nil),            // 8: api.user.v1.MoveGroupReq
	(*MoveGroupRes)(nil),            // 9: api.user.v1.MoveGroupRes
	(*SetEmailEnabledReq)(nil),      // 10: api.user.v1.SetEmailEnabledReq
	(*SetEmailEnabledRes)(nil),      // 11: api.user.v1.SetEmailEnabledRes
	(*GetUserIdsByGroupReq)(nil),    // 12: api.user.v1.GetUserIdsByGroupReq
	(*GetUserIdsByGroupRes)(nil),    // 13: api.user.v1.GetUserIdsByGroupRes
	(*GetByIdsReq)(nil),             // 14: api.user.v1.GetByIdsReq
	(*GetByIdsRes)(nil),             // 15: api.user.v1.GetByIdsRes
	(*GetByIdRes_Spiders)(nil),      // 16: api.user.v1.GetByIdRes.Spiders
	(*GetByNameRes_UserList)(nil),   // 17: api.user.v1.GetByNameRes.UserList
	(*GetListRes_List)(nil),         // 18: api.user.v1.GetListRes.List
	(*GetByIdsRes_UserProfile)(nil), // 19: api.user.v1.GetByIdsRes.UserProfile
}
var file_user_v1_profile_profile_proto_depIdxs = []int32{
	16, // 0: api.user.v1.GetByIdRes.spiders:type_name -> api.user.v1.GetByIdRes.Spiders
	17, // 1: api.user.v1.GetByNameRes.list:type_name -> api.user.v1.GetByNameRes.UserList
	18, // 2: api.user.v1.GetListRes.list:type_name -> api.user.v1.GetListRes.List
	19, // 3: api.user.v1.GetByIdsRes.profiles:type_name -> api.user.v1.GetByIdsRes.UserProfile
	0,  // 4: api.user.v1.Profile.GetById:input_type -> api.user.v1.GetByIdReq
	2,  // 5: api.user.v1.Profile.GetByName:input_type -> api.user.v1.GetByNameReq
	4,  // 6: api.user.v1.Profile.GetList:input_type -> api.user.v1.GetListReq
	6,  // 7: api.user.v1.Profile.Update:input_type -> api.user.v1.UpdateReq
	8,  // 8: api.user.v1.Profile.MoveGroup:input_type -> api.user.v1.MoveGroupReq
	10, // 9: api.user.v1.Profile.SetEmailEnabled:input_type -> api.user.v1.SetEmailEnabledReq
	12, // 10: api.user.v1.Profile.GetUserIdsByGroup:input_type -> api.user.v1.GetUserIdsByGroupReq
	14, // 11: api.user.v1.Profile.GetByIds:input_type -> api.user.v1.GetByIdsReq
	1,  // 12: api.user.v1.Profile.GetById:output_type -> api.user.v1.GetByIdRes
	3,  // 13: api.user.v1.Profile.GetByName:output_type -> api.user.v1.GetByNameRes
	5,  // 14: api.user.v1.Profile.GetList:output_type -> api.user.v1.GetListRes
	7,  // 15: api.user.v1.Profile.Update:output_type -> api.user.v1.UpdateRes
	9,  // 16: api.user.v1.Profile.MoveGroup:output_type -> api.user.v1.MoveGroupRes
	11, // 17: api.user.v1.Profile.SetEmailEnabled:output_type -> api.user.v1.SetEmailEnabledRes
	13, // 18: api.user.v1.Profile.GetUserIdsByGroup:output_type -> api.user.v1.GetUserIdsByGroupRes
	15, // 19: api.user.v1.Profile.GetByIds:output_type -> api.user.v1.GetByIdsRes
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_v1_profile_profile_proto_init() }
func file_user_v1_profile_profile_proto_init() {
	if File_user_v1_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_profile_profile_proto_rawDesc), len(file_user_v1_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_profile_profile_proto_goTypes,
		DependencyIndexes: file_user_v1_profile_profile_proto_depIdxs,
		MessageInfos:      file_user_v1_profile_profile_proto_msgTypes,
	}.Build()
	File_user_v1_profile_profile_proto = out.File
	file_user_v1_profile_profile_proto_goTypes = nil
	file_user_v1_profile_profile_proto_depIdxs = nil
}
