// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: user/v1/profile/profile.proto

package profile

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProfileGetById = "/api.user.v1.Profile/GetById"
const OperationProfileGetByName = "/api.user.v1.Profile/GetByName"
const OperationProfileGetList = "/api.user.v1.Profile/GetList"
const OperationProfileMoveGroup = "/api.user.v1.Profile/MoveGroup"
const OperationProfileSetEmailEnabled = "/api.user.v1.Profile/SetEmailEnabled"
const OperationProfileUpdate = "/api.user.v1.Profile/Update"

type ProfileHTTPServer interface {
	GetById(context.Context, *GetByIdReq) (*GetByIdRes, error)
	GetByName(context.Context, *GetByNameReq) (*GetByNameRes, error)
	GetList(context.Context, *GetListReq) (*GetListRes, error)
	MoveGroup(context.Context, *MoveGroupReq) (*MoveGroupRes, error)
	SetEmailEnabled(context.Context, *SetEmailEnabledReq) (*SetEmailEnabledRes, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
}

func RegisterProfileHTTPServer(s *http.Server, srv ProfileHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/user/profile/get-by-id", _Profile_GetById0_HTTP_Handler(srv))
	r.GET("/v1/user/profile/get-by-name", _Profile_GetByName0_HTTP_Handler(srv))
	r.GET("/v1/user/profile/list", _Profile_GetList0_HTTP_Handler(srv))
	r.POST("/v1/user/profile/update", _Profile_Update2_HTTP_Handler(srv))
	r.POST("/v1/user/profile/move-group", _Profile_MoveGroup0_HTTP_Handler(srv))
	r.POST("/v1/user/profile/set-email-enabled", _Profile_SetEmailEnabled0_HTTP_Handler(srv))
}

func _Profile_GetById0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetByIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileGetById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetById(ctx, req.(*GetByIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetByIdRes)
		return ctx.Result(200, reply)
	}
}

func _Profile_GetByName0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetByNameReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileGetByName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetByName(ctx, req.(*GetByNameReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetByNameRes)
		return ctx.Result(200, reply)
	}
}

func _Profile_GetList0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileGetList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetList(ctx, req.(*GetListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetListRes)
		return ctx.Result(200, reply)
	}
}

func _Profile_Update2_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRes)
		return ctx.Result(200, reply)
	}
}

func _Profile_MoveGroup0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MoveGroupReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileMoveGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MoveGroup(ctx, req.(*MoveGroupReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoveGroupRes)
		return ctx.Result(200, reply)
	}
}

func _Profile_SetEmailEnabled0_HTTP_Handler(srv ProfileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetEmailEnabledReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileSetEmailEnabled)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetEmailEnabled(ctx, req.(*SetEmailEnabledReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetEmailEnabledRes)
		return ctx.Result(200, reply)
	}
}

type ProfileHTTPClient interface {
	GetById(ctx context.Context, req *GetByIdReq, opts ...http.CallOption) (rsp *GetByIdRes, err error)
	GetByName(ctx context.Context, req *GetByNameReq, opts ...http.CallOption) (rsp *GetByNameRes, err error)
	GetList(ctx context.Context, req *GetListReq, opts ...http.CallOption) (rsp *GetListRes, err error)
	MoveGroup(ctx context.Context, req *MoveGroupReq, opts ...http.CallOption) (rsp *MoveGroupRes, err error)
	SetEmailEnabled(ctx context.Context, req *SetEmailEnabledReq, opts ...http.CallOption) (rsp *SetEmailEnabledRes, err error)
	Update(ctx context.Context, req *UpdateReq, opts ...http.CallOption) (rsp *UpdateRes, err error)
}

type ProfileHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileHTTPClient(client *http.Client) ProfileHTTPClient {
	return &ProfileHTTPClientImpl{client}
}

func (c *ProfileHTTPClientImpl) GetById(ctx context.Context, in *GetByIdReq, opts ...http.CallOption) (*GetByIdRes, error) {
	var out GetByIdRes
	pattern := "/v1/user/profile/get-by-id"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileGetById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileHTTPClientImpl) GetByName(ctx context.Context, in *GetByNameReq, opts ...http.CallOption) (*GetByNameRes, error) {
	var out GetByNameRes
	pattern := "/v1/user/profile/get-by-name"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileGetByName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileHTTPClientImpl) GetList(ctx context.Context, in *GetListReq, opts ...http.CallOption) (*GetListRes, error) {
	var out GetListRes
	pattern := "/v1/user/profile/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProfileGetList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileHTTPClientImpl) MoveGroup(ctx context.Context, in *MoveGroupReq, opts ...http.CallOption) (*MoveGroupRes, error) {
	var out MoveGroupRes
	pattern := "/v1/user/profile/move-group"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileMoveGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileHTTPClientImpl) SetEmailEnabled(ctx context.Context, in *SetEmailEnabledReq, opts ...http.CallOption) (*SetEmailEnabledRes, error) {
	var out SetEmailEnabledRes
	pattern := "/v1/user/profile/set-email-enabled"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileSetEmailEnabled))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileHTTPClientImpl) Update(ctx context.Context, in *UpdateReq, opts ...http.CallOption) (*UpdateRes, error) {
	var out UpdateRes
	pattern := "/v1/user/profile/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProfileUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
