// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: core/v1/spider/spider.proto

package spider

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSpiderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpiderReq) Reset() {
	*x = SetSpiderReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpiderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpiderReq) ProtoMessage() {}

func (x *SetSpiderReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpiderReq.ProtoReflect.Descriptor instead.
func (*SetSpiderReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{0}
}

func (x *SetSpiderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSpiderReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SetSpiderReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetSpiderRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpiderRep) Reset() {
	*x = SetSpiderRep{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpiderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpiderRep) ProtoMessage() {}

func (x *SetSpiderRep) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpiderRep.ProtoReflect.Descriptor instead.
func (*SetSpiderRep) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{1}
}

func (x *SetSpiderRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetSpiderRep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSpiderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderReq) Reset() {
	*x = GetSpiderReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderReq) ProtoMessage() {}

func (x *GetSpiderReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderReq.ProtoReflect.Descriptor instead.
func (*GetSpiderReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpiderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSpiderRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetSpiderRep_Data   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderRep) Reset() {
	*x = GetSpiderRep{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderRep) ProtoMessage() {}

func (x *GetSpiderRep) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderRep.ProtoReflect.Descriptor instead.
func (*GetSpiderRep) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpiderRep) GetData() []*GetSpiderRep_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         int64                  `protobuf:"varint,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRes) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type JobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobReq) Reset() {
	*x = JobReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReq) ProtoMessage() {}

func (x *JobReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReq.ProtoReflect.Descriptor instead.
func (*JobReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{6}
}

func (x *JobReq) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type JobInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             int64                  `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RequesterId       int64                  `protobuf:"varint,3,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	Source            string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	NeedAll           bool                   `protobuf:"varint,6,opt,name=needAll,proto3" json:"needAll,omitempty"`
	CurrentPlatform   string                 `protobuf:"bytes,7,opt,name=currentPlatform,proto3" json:"currentPlatform,omitempty"`
	TotalPlatforms    int32                  `protobuf:"varint,8,opt,name=totalPlatforms,proto3" json:"totalPlatforms,omitempty"`
	FinishedPlatforms int32                  `protobuf:"varint,9,opt,name=finishedPlatforms,proto3" json:"finishedPlatforms,omitempty"`
	Error             string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	StartedAt         int64                  `protobuf:"varint,12,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	FinishedAt        int64                  `protobuf:"varint,13,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{7}
}

func (x *JobInfo) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *JobInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JobInfo) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *JobInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobInfo) GetNeedAll() bool {
	if x != nil {
		return x.NeedAll
	}
	return false
}

func (x *JobInfo) GetCurrentPlatform() string {
	if x != nil {
		return x.CurrentPlatform
	}
	return ""
}

func (x *JobInfo) GetTotalPlatforms() int32 {
	if x != nil {
		return x.TotalPlatforms
	}
	return 0
}

func (x *JobInfo) GetFinishedPlatforms() int32 {
	if x != nil {
		return x.FinishedPlatforms
	}
	return 0
}

func (x *JobInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobInfo) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *JobInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type JobRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *JobInfo               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRes) Reset() {
	*x = JobRes{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRes) ProtoMessage() {}

func (x *JobRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRes.ProtoReflect.Descriptor instead.
func (*JobRes) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{8}
}

func (x *JobRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JobRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobRes) GetData() *JobInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type JobsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobsReq) Reset() {
	*x = JobsReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsReq) ProtoMessage() {}

func (x *JobsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsReq.ProtoReflect.Descriptor instead.
func (*JobsReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{9}
}

func (x *JobsReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *JobsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *JobsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *JobsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type JobsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*JobInfo             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobsRes) Reset() {
	*x = JobsRes{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsRes) ProtoMessage() {}

func (x *JobsRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsRes.ProtoReflect.Descriptor instead.
func (*JobsRes) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{10}
}

func (x *JobsRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JobsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobsRes) GetData() []*JobInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *JobsRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{11}
}

func (x *StatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SyncStatusInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Platform         string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastStartedAt    int64                  `protobuf:"varint,4,opt,name=lastStartedAt,proto3" json:"lastStartedAt,omitempty"`
	LastFinishedAt   int64                  `protobuf:"varint,5,opt,name=lastFinishedAt,proto3" json:"lastFinishedAt,omitempty"`
	LastSuccessAt    int64                  `protobuf:"varint,6,opt,name=lastSuccessAt,proto3" json:"lastSuccessAt,omitempty"`
	LastError        string                 `protobuf:"bytes,7,opt,name=lastError,proto3" json:"lastError,omitempty"`
	LastFetchedCount int64                  `protobuf:"varint,8,opt,name=lastFetchedCount,proto3" json:"lastFetchedCount,omitempty"`
	IsStale          bool                   `protobuf:"varint,9,opt,name=isStale,proto3" json:"isStale,omitempty"`
	CanViewError     bool                   `protobuf:"varint,10,opt,name=canViewError,proto3" json:"canViewError,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncStatusInfo) Reset() {
	*x = SyncStatusInfo{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatusInfo) ProtoMessage() {}

func (x *SyncStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatusInfo.ProtoReflect.Descriptor instead.
func (*SyncStatusInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{12}
}

func (x *SyncStatusInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SyncStatusInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SyncStatusInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncStatusInfo) GetLastStartedAt() int64 {
	if x != nil {
		return x.LastStartedAt
	}
	return 0
}

func (x *SyncStatusInfo) GetLastFinishedAt() int64 {
	if x != nil {
		return x.LastFinishedAt
	}
	return 0
}

func (x *SyncStatusInfo) GetLastSuccessAt() int64 {
	if x != nil {
		return x.LastSuccessAt
	}
	return 0
}

func (x *SyncStatusInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *SyncStatusInfo) GetLastFetchedCount() int64 {
	if x != nil {
		return x.LastFetchedCount
	}
	return 0
}

func (x *SyncStatusInfo) GetIsStale() bool {
	if x != nil {
		return x.IsStale
	}
	return false
}

func (x *SyncStatusInfo) GetCanViewError() bool {
	if x != nil {
		return x.CanViewError
	}
	return false
}

func (x *SyncStatusInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type StatusRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data              []*SyncStatusInfo      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	StaleAfterSeconds int64                  `protobuf:"varint,4,opt,name=staleAfterSeconds,proto3" json:"staleAfterSeconds,omitempty"`
	GeneratedAt       int64                  `protobuf:"varint,5,opt,name=generatedAt,proto3" json:"generatedAt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusRes) Reset() {
	*x = StatusRes{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRes) ProtoMessage() {}

func (x *StatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRes.ProtoReflect.Descriptor instead.
func (*StatusRes) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{13}
}

func (x *StatusRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusRes) GetData() []*SyncStatusInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StatusRes) GetStaleAfterSeconds() int64 {
	if x != nil {
		return x.StaleAfterSeconds
	}
	return 0
}

func (x *StatusRes) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

type GetSpiderRep_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderRep_Data) Reset() {
	*x = GetSpiderRep_Data{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderRep_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderRep_Data) ProtoMessage() {}

func (x *GetSpiderRep_Data) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderRep_Data.ProtoReflect.Descriptor instead.
func (*GetSpiderRep_Data) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetSpiderRep_Data) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetSpiderRep_Data) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_core_v1_spider_spider_proto protoreflect.FileDescriptor

const file_core_v1_spider_spider_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/v1/spider/spider.proto\x12\x12api.core.v1.spider\x1a\x1cgoogle/api/annotations.proto\"^\n" +
	"\fSetSpiderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"<\n" +
	"\fSetSpiderRep\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\fGetSpiderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x89\x01\n" +
	"\fGetSpiderRep\x129\n" +
	"\x04data\x18\x01 \x03(\v2%.api.core.v1.spider.GetSpiderRep.DataR\x04data\x1a>\n" +
	"\x04Data\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"@\n" +
	"\tUpdateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"O\n" +
	"\tUpdateRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05jobId\x18\x03 \x01(\x03R\x05jobId\"\x1e\n" +
	"\x06JobReq\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\x03R\x05jobId\"\xb3\x03\n" +
	"\aJobInfo\x12\x14\n" +
	"\x05jobId\x18\x01 \x01(\x03R\x05jobId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12 \n" +
	"\vrequesterId\x18\x03 \x01(\x03R\vrequesterId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aneedAll\x18\x06 \x01(\bR\aneedAll\x12(\n" +
	"\x0fcurrentPlatform\x18\a \x01(\tR\x0fcurrentPlatform\x12&\n" +
	"\x0etotalPlatforms\x18\b \x01(\x05R\x0etotalPlatforms\x12,\n" +
	"\x11finishedPlatforms\x18\t \x01(\x05R\x11finishedPlatforms\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tstartedAt\x18\f \x01(\x03R\tstartedAt\x12\x1e\n" +
	"\n" +
	"finishedAt\x18\r \x01(\x03R\n" +
	"finishedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\x03R\tupdatedAt\"g\n" +
	"\x06JobRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.api.core.v1.spider.JobInfoR\x04data\"\x7f\n" +
	"\aJobsReq\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\x03R\x06userId\"~\n" +
	"\aJobsRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.api.core.v1.spider.JobInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"#\n" +
	"\tStatusReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xfa\x02\n" +
	"\x0eSyncStatusInfo\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12$\n" +
	"\rlastStartedAt\x18\x04 \x01(\x03R\rlastStartedAt\x12&\n" +
	"\x0elastFinishedAt\x18\x05 \x01(\x03R\x0elastFinishedAt\x12$\n" +
	"\rlastSuccessAt\x18\x06 \x01(\x03R\rlastSuccessAt\x12\x1c\n" +
	"\tlastError\x18\a \x01(\tR\tlastError\x12*\n" +
	"\x10lastFetchedCount\x18\b \x01(\x03R\x10lastFetchedCount\x12\x18\n" +
	"\aisStale\x18\t \x01(\bR\aisStale\x12\"\n" +
	"\fcanViewError\x18\n" +
	" \x01(\bR\fcanViewError\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\x03R\tupdatedAt\"\xc1\x01\n" +
	"\tStatusRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".api.core.v1.spider.SyncStatusInfoR\x04data\x12,\n" +
	"\x11staleAfterSeconds\x18\x04 \x01(\x03R\x11staleAfterSeconds\x12 \n" +
	"\vgeneratedAt\x18\x05 \x01(\x03R\vgeneratedAt2\xdb\x04\n" +
	"\x06Spider\x12o\n" +
	"\tSetSpider\x12 .api.core.v1.spider.SetSpiderReq\x1a .api.core.v1.spider.SetSpiderRep\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/core/spider/set\x12Q\n" +
	"\tGetSpider\x12 .api.core.v1.spider.GetSpiderReq\x1a .api.core.v1.spider.GetSpiderRep\"\x00\x12i\n" +
	"\x06Update\x12\x1d.api.core.v1.spider.UpdateReq\x1a\x1d.api.core.v1.spider.UpdateRes\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/core/spider/update\x12Z\n" +
	"\x03Job\x12\x1a.api.core.v1.spider.JobReq\x1a\x1a.api.core.v1.spider.JobRes\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/core/spider/job\x12^\n" +
	"\x04Jobs\x12\x1b.api.core.v1.spider.JobsReq\x1a\x1b.api.core.v1.spider.JobsRes\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/core/spider/jobs\x12f\n" +
	"\x06Status\x12\x1d.api.core.v1.spider.StatusReq\x1a\x1d.api.core.v1.spider.StatusRes\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/core/spider/statusB;\n" +
	"\x12api.core.v1.spiderP\x01Z#cwxu-algo/api/core/v1/spider;spiderb\x06proto3"

var (
	file_core_v1_spider_spider_proto_rawDescOnce sync.Once
	file_core_v1_spider_spider_proto_rawDescData []byte
)

func file_core_v1_spider_spider_proto_rawDescGZIP() []byte {
	file_core_v1_spider_spider_proto_rawDescOnce.Do(func() {
		file_core_v1_spider_spider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_spider_spider_proto_rawDesc), len(file_core_v1_spider_spider_proto_rawDesc)))
	})
	return file_core_v1_spider_spider_proto_rawDescData
}

var file_core_v1_spider_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_core_v1_spider_spider_proto_goTypes = []any{
	(*SetSpiderReq)(nil),      // 0: api.core.v1.spider.SetSpiderReq
	(*SetSpiderRep)(nil),      // 1: api.core.v1.spider.SetSpiderRep
	(*GetSpiderReq)(nil),      // 2: api.core.v1.spider.GetSpiderReq
	(*GetSpiderRep)(nil),      // 3: api.core.v1.spider.GetSpiderRep
	(*UpdateReq)(nil),         // 4: api.core.v1.spider.UpdateReq
	(*UpdateRes)(nil),         // 5: api.core.v1.spider.UpdateRes
	(*JobReq)(nil),            // 6: api.core.v1.spider.JobReq
	(*JobInfo)(nil),           // 7: api.core.v1.spider.JobInfo
	(*JobRes)(nil),            // 8: api.core.v1.spider.JobRes
	(*JobsReq)(nil),           // 9: api.core.v1.spider.JobsReq
	(*JobsRes)(nil),           // 10: api.core.v1.spider.JobsRes
	(*StatusReq)(nil),         // 11: api.core.v1.spider.StatusReq
	(*SyncStatusInfo)(nil),    // 12: api.core.v1.spider.SyncStatusInfo
	(*StatusRes)(nil),         // 13: api.core.v1.spider.StatusRes
	(*GetSpiderRep_Data)(nil), // 14: api.core.v1.spider.GetSpiderRep.Data
}
var file_core_v1_spider_spider_proto_depIdxs = []int32{
	14, // 0: api.core.v1.spider.GetSpiderRep.data:type_name -> api.core.v1.spider.GetSpiderRep.Data
	7,  // 1: api.core.v1.spider.JobRes.data:type_name -> api.core.v1.spider.JobInfo
	7,  // 2: api.core.v1.spider.JobsRes.data:type_name -> api.core.v1.spider.JobInfo
	12, // 3: api.core.v1.spider.StatusRes.data:type_name -> api.core.v1.spider.SyncStatusInfo
	0,  // 4: api.core.v1.spider.Spider.SetSpider:input_type -> api.core.v1.spider.SetSpiderReq
	2,  // 5: api.core.v1.spider.Spider.GetSpider:input_type -> api.core.v1.spider.GetSpiderReq
	4,  // 6: api.core.v1.spider.Spider.Update:input_type -> api.core.v1.spider.UpdateReq
	6,  // 7: api.core.v1.spider.Spider.Job:input_type -> api.core.v1.spider.JobReq
	9,  // 8: api.core.v1.spider.Spider.Jobs:input_type -> api.core.v1.spider.JobsReq
	11, // 9: api.core.v1.spider.Spider.Status:input_type -> api.core.v1.spider.StatusReq
	1,  // 10: api.core.v1.spider.Spider.SetSpider:output_type -> api.core.v1.spider.SetSpiderRep
	3,  // 11: api.core.v1.spider.Spider.GetSpider:output_type -> api.core.v1.spider.GetSpiderRep
	5,  // 12: api.core.v1.spider.Spider.Update:output_type -> api.core.v1.spider.UpdateRes
	8,  // 13: api.core.v1.spider.Spider.Job:output_type -> api.core.v1.spider.JobRes
	10, // 14: api.core.v1.spider.Spider.Jobs:output_type -> api.core.v1.spider.JobsRes
	13, // 15: api.core.v1.spider.Spider.Status:output_type -> api.core.v1.spider.StatusRes
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_core_v1_spider_spider_proto_init() }
func file_core_v1_spider_spider_proto_init() {
	if File_core_v1_spider_spider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_spider_spider_proto_rawDesc), len(file_core_v1_spider_spider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_spider_spider_proto_goTypes,
		DependencyIndexes: file_core_v1_spider_spider_proto_depIdxs,
		MessageInfos:      file_core_v1_spider_spider_proto_msgTypes,
	}.Build()
	File_core_v1_spider_spider_proto = out.File
	file_core_v1_spider_spider_proto_goTypes = nil
	file_core_v1_spider_spider_proto_depIdxs = nil
}
