// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: core/v1/spider/spider.proto

package spider

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSpiderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpiderReq) Reset() {
	*x = SetSpiderReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpiderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpiderReq) ProtoMessage() {}

func (x *SetSpiderReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpiderReq.ProtoReflect.Descriptor instead.
func (*SetSpiderReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{0}
}

func (x *SetSpiderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSpiderReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SetSpiderReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetSpiderRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpiderRep) Reset() {
	*x = SetSpiderRep{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpiderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpiderRep) ProtoMessage() {}

func (x *SetSpiderRep) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpiderRep.ProtoReflect.Descriptor instead.
func (*SetSpiderRep) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{1}
}

func (x *SetSpiderRep) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetSpiderRep) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSpiderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderReq) Reset() {
	*x = GetSpiderReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderReq) ProtoMessage() {}

func (x *GetSpiderReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderReq.ProtoReflect.Descriptor instead.
func (*GetSpiderReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpiderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSpiderRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetSpiderRep_Data   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderRep) Reset() {
	*x = GetSpiderRep{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderRep) ProtoMessage() {}

func (x *GetSpiderRep) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderRep.ProtoReflect.Descriptor instead.
func (*GetSpiderRep) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpiderRep) GetData() []*GetSpiderRep_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSpiderRep_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpiderRep_Data) Reset() {
	*x = GetSpiderRep_Data{}
	mi := &file_core_v1_spider_spider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpiderRep_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpiderRep_Data) ProtoMessage() {}

func (x *GetSpiderRep_Data) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_spider_spider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpiderRep_Data.ProtoReflect.Descriptor instead.
func (*GetSpiderRep_Data) Descriptor() ([]byte, []int) {
	return file_core_v1_spider_spider_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetSpiderRep_Data) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetSpiderRep_Data) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_core_v1_spider_spider_proto protoreflect.FileDescriptor

const file_core_v1_spider_spider_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/v1/spider/spider.proto\x12\x12api.core.v1.spider\x1a\x1cgoogle/api/annotations.proto\"^\n" +
	"\fSetSpiderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"<\n" +
	"\fSetSpiderRep\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\fGetSpiderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x89\x01\n" +
	"\fGetSpiderRep\x129\n" +
	"\x04data\x18\x01 \x03(\v2%.api.core.v1.spider.GetSpiderRep.DataR\x04data\x1a>\n" +
	"\x04Data\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"$\n" +
	"\tUpdateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"9\n" +
	"\tUpdateRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x02\n" +
	"\x06Spider\x12o\n" +
	"\tSetSpider\x12 .api.core.v1.spider.SetSpiderReq\x1a .api.core.v1.spider.SetSpiderRep\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/core/spider/set\x12Q\n" +
	"\tGetSpider\x12 .api.core.v1.spider.GetSpiderReq\x1a .api.core.v1.spider.GetSpiderRep\"\x00\x12i\n" +
	"\x06Update\x12\x1d.api.core.v1.spider.UpdateReq\x1a\x1d.api.core.v1.spider.UpdateRes\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/core/spider/updateB;\n" +
	"\x12api.core.v1.spiderP\x01Z#cwxu-algo/api/core/v1/spider;spiderb\x06proto3"

var (
	file_core_v1_spider_spider_proto_rawDescOnce sync.Once
	file_core_v1_spider_spider_proto_rawDescData []byte
)

func file_core_v1_spider_spider_proto_rawDescGZIP() []byte {
	file_core_v1_spider_spider_proto_rawDescOnce.Do(func() {
		file_core_v1_spider_spider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_spider_spider_proto_rawDesc), len(file_core_v1_spider_spider_proto_rawDesc)))
	})
	return file_core_v1_spider_spider_proto_rawDescData
}

var file_core_v1_spider_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_v1_spider_spider_proto_goTypes = []any{
	(*SetSpiderReq)(nil),      // 0: api.core.v1.spider.SetSpiderReq
	(*SetSpiderRep)(nil),      // 1: api.core.v1.spider.SetSpiderRep
	(*GetSpiderReq)(nil),      // 2: api.core.v1.spider.GetSpiderReq
	(*GetSpiderRep)(nil),      // 3: api.core.v1.spider.GetSpiderRep
	(*UpdateReq)(nil),         // 4: api.core.v1.spider.UpdateReq
	(*UpdateRes)(nil),         // 5: api.core.v1.spider.UpdateRes
	(*GetSpiderRep_Data)(nil), // 6: api.core.v1.spider.GetSpiderRep.Data
}
var file_core_v1_spider_spider_proto_depIdxs = []int32{
	6, // 0: api.core.v1.spider.GetSpiderRep.data:type_name -> api.core.v1.spider.GetSpiderRep.Data
	0, // 1: api.core.v1.spider.Spider.SetSpider:input_type -> api.core.v1.spider.SetSpiderReq
	2, // 2: api.core.v1.spider.Spider.GetSpider:input_type -> api.core.v1.spider.GetSpiderReq
	4, // 3: api.core.v1.spider.Spider.Update:input_type -> api.core.v1.spider.UpdateReq
	1, // 4: api.core.v1.spider.Spider.SetSpider:output_type -> api.core.v1.spider.SetSpiderRep
	3, // 5: api.core.v1.spider.Spider.GetSpider:output_type -> api.core.v1.spider.GetSpiderRep
	5, // 6: api.core.v1.spider.Spider.Update:output_type -> api.core.v1.spider.UpdateRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_spider_spider_proto_init() }
func file_core_v1_spider_spider_proto_init() {
	if File_core_v1_spider_spider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_spider_spider_proto_rawDesc), len(file_core_v1_spider_spider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_spider_spider_proto_goTypes,
		DependencyIndexes: file_core_v1_spider_spider_proto_depIdxs,
		MessageInfos:      file_core_v1_spider_spider_proto_msgTypes,
	}.Build()
	File_core_v1_spider_spider_proto = out.File
	file_core_v1_spider_spider_proto_goTypes = nil
	file_core_v1_spider_spider_proto_depIdxs = nil
}
