// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: core/v1/spider/spider.proto

package spider

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSpiderJob = "/api.core.v1.spider.Spider/Job"
const OperationSpiderJobs = "/api.core.v1.spider.Spider/Jobs"
const OperationSpiderSetSpider = "/api.core.v1.spider.Spider/SetSpider"
const OperationSpiderStatus = "/api.core.v1.spider.Spider/Status"
const OperationSpiderUpdate = "/api.core.v1.spider.Spider/Update"

type SpiderHTTPServer interface {
	Job(context.Context, *JobReq) (*JobRes, error)
	Jobs(context.Context, *JobsReq) (*JobsRes, error)
	SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error)
	Status(context.Context, *StatusReq) (*StatusRes, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
}

func RegisterSpiderHTTPServer(s *http.Server, srv SpiderHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/core/spider/set", _Spider_SetSpider0_HTTP_Handler(srv))
	r.POST("/v1/core/spider/update", _Spider_Update1_HTTP_Handler(srv))
	r.GET("/v1/core/spider/job", _Spider_Job0_HTTP_Handler(srv))
	r.GET("/v1/core/spider/jobs", _Spider_Jobs0_HTTP_Handler(srv))
	r.GET("/v1/core/spider/status", _Spider_Status0_HTTP_Handler(srv))
}

func _Spider_SetSpider0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetSpiderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderSetSpider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetSpider(ctx, req.(*SetSpiderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetSpiderRep)
		return ctx.Result(200, reply)
	}
}

func _Spider_Update1_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRes)
		return ctx.Result(200, reply)
	}
}

func _Spider_Job0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JobReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Job(ctx, req.(*JobReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobRes)
		return ctx.Result(200, reply)
	}
}

func _Spider_Jobs0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JobsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderJobs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Jobs(ctx, req.(*JobsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobsRes)
		return ctx.Result(200, reply)
	}
}

func _Spider_Status0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StatusReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Status(ctx, req.(*StatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatusRes)
		return ctx.Result(200, reply)
	}
}

type SpiderHTTPClient interface {
	Job(ctx context.Context, req *JobReq, opts ...http.CallOption) (rsp *JobRes, err error)
	Jobs(ctx context.Context, req *JobsReq, opts ...http.CallOption) (rsp *JobsRes, err error)
	SetSpider(ctx context.Context, req *SetSpiderReq, opts ...http.CallOption) (rsp *SetSpiderRep, err error)
	Status(ctx context.Context, req *StatusReq, opts ...http.CallOption) (rsp *StatusRes, err error)
	Update(ctx context.Context, req *UpdateReq, opts ...http.CallOption) (rsp *UpdateRes, err error)
}

type SpiderHTTPClientImpl struct {
	cc *http.Client
}

func NewSpiderHTTPClient(client *http.Client) SpiderHTTPClient {
	return &SpiderHTTPClientImpl{client}
}

func (c *SpiderHTTPClientImpl) Job(ctx context.Context, in *JobReq, opts ...http.CallOption) (*JobRes, error) {
	var out JobRes
	pattern := "/v1/core/spider/job"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSpiderJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpiderHTTPClientImpl) Jobs(ctx context.Context, in *JobsReq, opts ...http.CallOption) (*JobsRes, error) {
	var out JobsRes
	pattern := "/v1/core/spider/jobs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSpiderJobs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpiderHTTPClientImpl) SetSpider(ctx context.Context, in *SetSpiderReq, opts ...http.CallOption) (*SetSpiderRep, error) {
	var out SetSpiderRep
	pattern := "/v1/core/spider/set"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSpiderSetSpider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpiderHTTPClientImpl) Status(ctx context.Context, in *StatusReq, opts ...http.CallOption) (*StatusRes, error) {
	var out StatusRes
	pattern := "/v1/core/spider/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSpiderStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpiderHTTPClientImpl) Update(ctx context.Context, in *UpdateReq, opts ...http.CallOption) (*UpdateRes, error) {
	var out UpdateRes
	pattern := "/v1/core/spider/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSpiderUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
