// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: core/v1/spider/spider.proto

package spider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spider_SetSpider_FullMethodName = "/api.core.v1.spider.Spider/SetSpider"
	Spider_GetSpider_FullMethodName = "/api.core.v1.spider.Spider/GetSpider"
	Spider_Update_FullMethodName    = "/api.core.v1.spider.Spider/Update"
	Spider_Job_FullMethodName       = "/api.core.v1.spider.Spider/Job"
	Spider_Jobs_FullMethodName      = "/api.core.v1.spider.Spider/Jobs"
	Spider_Status_FullMethodName    = "/api.core.v1.spider.Spider/Status"
)

// SpiderClient is the client API for Spider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiderClient interface {
	SetSpider(ctx context.Context, in *SetSpiderReq, opts ...grpc.CallOption) (*SetSpiderRep, error)
	GetSpider(ctx context.Context, in *GetSpiderReq, opts ...grpc.CallOption) (*GetSpiderRep, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error)
	Job(ctx context.Context, in *JobReq, opts ...grpc.CallOption) (*JobRes, error)
	Jobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsRes, error)
	Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusRes, error)
}

type spiderClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderClient(cc grpc.ClientConnInterface) SpiderClient {
	return &spiderClient{cc}
}

func (c *spiderClient) SetSpider(ctx context.Context, in *SetSpiderReq, opts ...grpc.CallOption) (*SetSpiderRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSpiderRep)
	err := c.cc.Invoke(ctx, Spider_SetSpider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) GetSpider(ctx context.Context, in *GetSpiderReq, opts ...grpc.CallOption) (*GetSpiderRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpiderRep)
	err := c.cc.Invoke(ctx, Spider_GetSpider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRes)
	err := c.cc.Invoke(ctx, Spider_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) Job(ctx context.Context, in *JobReq, opts ...grpc.CallOption) (*JobRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobRes)
	err := c.cc.Invoke(ctx, Spider_Job_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) Jobs(ctx context.Context, in *JobsReq, opts ...grpc.CallOption) (*JobsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsRes)
	err := c.cc.Invoke(ctx, Spider_Jobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiderClient) Status(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusRes)
	err := c.cc.Invoke(ctx, Spider_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServer is the server API for Spider service.
// All implementations must embed UnimplementedSpiderServer
// for forward compatibility.
type SpiderServer interface {
	SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error)
	GetSpider(context.Context, *GetSpiderReq) (*GetSpiderRep, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
	Job(context.Context, *JobReq) (*JobRes, error)
	Jobs(context.Context, *JobsReq) (*JobsRes, error)
	Status(context.Context, *StatusReq) (*StatusRes, error)
	mustEmbedUnimplementedSpiderServer()
}

// UnimplementedSpiderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpiderServer struct{}

func (UnimplementedSpiderServer) SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpider not implemented")
}
func (UnimplementedSpiderServer) GetSpider(context.Context, *GetSpiderReq) (*GetSpiderRep, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpider not implemented")
}
func (UnimplementedSpiderServer) Update(context.Context, *UpdateReq) (*UpdateRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSpiderServer) Job(context.Context, *JobReq) (*JobRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Job not implemented")
}
func (UnimplementedSpiderServer) Jobs(context.Context, *JobsReq) (*JobsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Jobs not implemented")
}
func (UnimplementedSpiderServer) Status(context.Context, *StatusReq) (*StatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSpiderServer) mustEmbedUnimplementedSpiderServer() {}
func (UnimplementedSpiderServer) testEmbeddedByValue()                {}

// UnsafeSpiderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiderServer will
// result in compilation errors.
type UnsafeSpiderServer interface {
	mustEmbedUnimplementedSpiderServer()
}

func RegisterSpiderServer(s grpc.ServiceRegistrar, srv SpiderServer) {
	// If the following call panics, it indicates UnimplementedSpiderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spider_ServiceDesc, srv)
}

func _Spider_SetSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).SetSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_SetSpider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).SetSpider(ctx, req.(*SetSpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_GetSpider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpiderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).GetSpider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_GetSpider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).GetSpider(ctx, req.(*GetSpiderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_Job_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Job(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_Job_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Job(ctx, req.(*JobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_Jobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Jobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_Jobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Jobs(ctx, req.(*JobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Spider_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spider_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Status(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Spider_ServiceDesc is the grpc.ServiceDesc for Spider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.core.v1.spider.Spider",
	HandlerType: (*SpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSpider",
			Handler:    _Spider_SetSpider_Handler,
		},
		{
			MethodName: "GetSpider",
			Handler:    _Spider_GetSpider_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Spider_Update_Handler,
		},
		{
			MethodName: "Job",
			Handler:    _Spider_Job_Handler,
		},
		{
			MethodName: "Jobs",
			Handler:    _Spider_Jobs_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Spider_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/spider/spider.proto",
}
