// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: core/v1/spider/spider.proto

package spider

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSpiderSetSpider = "/api.core.v1.spider.Spider/SetSpider"
const OperationSpiderUpdate = "/api.core.v1.spider.Spider/Update"

type SpiderHTTPServer interface {
	SetSpider(context.Context, *SetSpiderReq) (*SetSpiderRep, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
}

func RegisterSpiderHTTPServer(s *http.Server, srv SpiderHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/core/spider/set", _Spider_SetSpider0_HTTP_Handler(srv))
	r.POST("/v1/core/spider/update", _Spider_Update0_HTTP_Handler(srv))
}

func _Spider_SetSpider0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetSpiderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderSetSpider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetSpider(ctx, req.(*SetSpiderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetSpiderRep)
		return ctx.Result(200, reply)
	}
}

func _Spider_Update0_HTTP_Handler(srv SpiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpiderUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UpdateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRes)
		return ctx.Result(200, reply)
	}
}

type SpiderHTTPClient interface {
	SetSpider(ctx context.Context, req *SetSpiderReq, opts ...http.CallOption) (rsp *SetSpiderRep, err error)
	Update(ctx context.Context, req *UpdateReq, opts ...http.CallOption) (rsp *UpdateRes, err error)
}

type SpiderHTTPClientImpl struct {
	cc *http.Client
}

func NewSpiderHTTPClient(client *http.Client) SpiderHTTPClient {
	return &SpiderHTTPClientImpl{client}
}

func (c *SpiderHTTPClientImpl) SetSpider(ctx context.Context, in *SetSpiderReq, opts ...http.CallOption) (*SetSpiderRep, error) {
	var out SetSpiderRep
	pattern := "/v1/core/spider/set"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSpiderSetSpider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpiderHTTPClientImpl) Update(ctx context.Context, in *UpdateReq, opts ...http.CallOption) (*UpdateRes, error) {
	var out UpdateRes
	pattern := "/v1/core/spider/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSpiderUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
